### ISSUE TITLE
[Bug ?]  Editing the "Url Title" field of the Root Page, cannot return at default value (empty or "/") Url.

### ISSUE THREAD

**Issue by portal7** [Orckestra/C1-CMS-Foundation#410]
I am once again facing this situation and that is why I report it.

This is the scenario.

I open the homepage, I edit the field "Url Title" and I put a value, say .... "Home" .... ok, every time someone references the root url ("/") goes home Page. (See figure 1)
![1](https://cloud.githubusercontent.com/assets/1530909/23653935/2e649142-030d-11e7-9c15-748976fe8235.png)

Suppose we now try to return to the original value ("/") and no longer use the specified value (see figure 2)
![2](https://cloud.githubusercontent.com/assets/1530909/23653944/357f6240-030d-11e7-947c-afb70d1ad030.png)

What happens is that regardless of what it does, it continues to point to "Home" and no longer to the Site Root ("/"). Returning error 404
![3](https://cloud.githubusercontent.com/assets/1530909/23653947/395245cc-030d-11e7-9524-cf730f499f1d.png)

(Figure 3)

**Comment by burningice2866** [comment]
@portal7 The issue arises because C1 uses permanent redirect when you request the root page using a url that works but isn't the correct one. This redirect is then cached by browser since its permanent, and later on will cause the behavior you're experiencing if you change the url-title.

You can solve it by

 1. Request the root page in a Private/Incognito browser session or
 2. Empty your browsers cache
