### ISSUE TITLE
[Question] Where does C1 read the user permissions from on login.

### ISSUE THREAD

**Issue by InderbirH** [Orckestra/C1-CMS-Foundation#452]
How does c1 know which content the user has permission to?/ Where does it read in the userpermissions to see which pages the user has access to; file name and line number?

Thanks.

**Comment by InderbirH** [comment]
@mawtex additionally, is it read separately like the user perspectives are, or inherited from something else?

**Comment by mawtex** [comment]
Permissions can be defined per node in the tree, per user/group. Permissions are inherited down the tree. The perspectives in the CMS Console are nodes, with sub trees under them - and all perspectives are under under a common root node. Permissions on the common root node are considered "global permissions", since they get inherited to all nodes (unless overwritten further down). [Documentation of setting permissions available here](http://users.c1.orckestra.com/Superuser/Security/UserGlobalPermissions).

To resolve a permission, you need a "entity token" (all tree nodes have one)  and a "user login".

Since sub-trees in the CMS Console come from all kinds of providers and multiple nodes may share entity tokens (imagine a piece of data being shown at more than one place), there is a "hook system" that allows one sub tree to be hooked to a node on another, thus propagating permissions. 

Permissions are stored in the CMS Data types named IUserPermission* and IUserGroupPermission* - you can find the types in https://github.com/Orckestra/C1-CMS-Foundation/tree/dev/Composite/Data/Types

**Comment by inder159** [comment]
@mawtex thank you for the quick response. I believe theirs some miscommunication (on my part), I meant when a user logs into composite where does it read the users permissions so the correct sites (the ones the user has permission to edit etc...) are displayed in the content section?

Thanks.

**Comment by mawtex** [comment]
The raw data to resolve permissions is read from the data type I mentioned. At API level, the mentioned PermissionsFacade is used.
