### ISSUE TITLE
Dashes ("-") being converted weird url encoded character

### ISSUE THREAD

**Issue by ThisIsMeJKB** [Orckestra/C1-CMS-Foundation#486]
I'm using **InternalUrl** and **RouteSegment** attributes on a few Static Data Types to leverage linking to data items, but I'm seeing some weird behavior.

I have a **Department** type defined with the **InternalUrl("department")** attribute specified at the type-level and the **RouteSegment(0)** specified on the one property I want to be used in the PathInfo.

The problem is, urls keep being rendered with **%7c2D** in the place of the dashes in the url. So, the "Human Resources" Department that should be being rendered as "/departments/human-resources" is being rendered as "/departments/human%7c2Dresources" when I have "~/department([DEPT_GUID])".....which is causing links to break throughout the site because %7c2D is not  the url encoded version of "-".

I just upgraded my site from v4.3 to v6.2 and attempted to add in the Data Item Linking (since it wasn't supported before v5) and this is what I'm getting. I've followed the direction outlined in the online help docs, using the RoutedData.GetDefaultMapper inside the app startup routing to get everything registered.

**Comment by DBailey635** [comment]
I found the same issue when I was building Page Datafolders with InternalUrl. I ended up adding RegEx validation to those fields used to build the URL: `^[\w\d\s]+$`

**Comment by mawtex** [comment]
The issue is that the code transforming a string into a valid path _must_ be bi-directional. The nitty gritty of it all is that this code will replace spaces with dash (-) and so it needs to first replace dash with something else. Original dash (-) values are ultimately substituted with |2D which encoded become %7c2D.

Seemingly this have a breaking effect on iPhone:
> Dashes ("-") in urls are being rendered with %7c2D in the place of the dashes which causes the "Illegal characters in path" error when accessed on an iPhone. 

Repro to show this URL behavior:
1. Create a PageFolder data type, named Maw.Mawtest, with a string field "Title", that is used in URLs (check "use in data urls" on field in type editor)
2. Create a Razor function using code below
3. Attach the data type to a page and add one or more data items, one having a normal dash in the title
4. Add the Razor function to the page content and view the page.


```
@inherits RazorFunction
@functions {
    public RoutedData<Maw.Mawtest> ListData { get; set; }
}
<html xmlns="http://www.w3.org/1999/xhtml">
    <head />
    <body>
        <ul>
            @foreach( var item in ListData.List)
            {
                <li>
                    <a href="@ListData.ItemUrl(item)">@ListData.ItemUrl(item)</a> <br/>
                    @item.Title
                </li>
            }
        </ul>
    </body>
</html>
```

**Comment by mawtex** [comment]
The above mentioned issue with iPhone failing to render URLs where path contains %7c  or | is affecting mobile devices in general, and seems to be an asp.net behavior and very easy to reproduce.

I've raised the issue here https://forums.asp.net/t/2141541.aspx?+Illegal+characters+in+path+when+request+come+from+mobile+device+like+iPhone+Android+emulator

**Comment by mawtex** [comment]
Related commit https://github.com/Orckestra/C1-CMS-Foundation/commit/67effa30b45570386b50d5b9e41baa5bb1c633eb
