### ISSUE TITLE
C1 Source - CodeFile vs CodeBehind

### ISSUE THREAD

**Issue by ai-fwd** [Orckestra/C1-CMS-Foundation#503]
In the source the Websites is a WAP which builds and runs successfully. However, i noticed that the .aspx/.ascx files use the CodeFile  vs CodeBehind syntax and some files are missing or have an out of date designer.cs. It was my understanding that WAPs require the "CodeBehind" syntax and the *.designer.cs.

Was there a reason for not changing to CodeBehind and excluding the designer.cs files?

**Comment by napernik** [comment]
That's a really good question.

The CodeBehind model would require shipping a Composite.Website.dll as well, that would provide additional obstacles during development, deployment, as well as providing patches/upgrade packages. At least it was true about 8-10 years ago, when most of the aspx/asmx code was written. Back then the repository wasn't GIT based and it was also closed source, so giving a partner/client an option to modify one of the aspx.cs files to get a hotfix/patch was a viable solution. 

The reason for designer.cs being out of date - is due to bugs in Visual Studio, it would often not update the designer.cs when aspx file is updated. It could have be caused by having multiple web.config files (the one in the root and the one in /Composite).

Having the website project as WAP has more of a validation by compilation purpose, as well a executing pre/post-build steps. The actual DLL you get as a result isn't used, as you can see here: https://github.com/Orckestra/C1-AzureWebApp-Template/tree/master/Bin

It is of less importance now to change it as we aim not to use WebForms when developing new features.
