### ISSUE TITLE
Equivalent of SitemapNavigator.CurrentHomePageNode for logged in user

### ISSUE THREAD

**Issue by ai-fwd** [Orckestra/C1-CMS-Foundation#556]
I want to be able to provide functions that are tailored to the current user. In order to do that I need access to the user's id in my world. To get that id I need to access a PageDataFolder that hangs of the site HomePage. 

Is there any way to get the set of HomePageIds they have access to when editing via the console?

Right now i'm having to use the username to query the DB directly to get what i need but hoping there is a simpler way.

**Comment by burningice2866** [comment]
@ai-fwd thats a tricky one since pages per se doesn't have permissions, its only the Tree Elements in the console representing the page that has the permission.

You need to take a look at [PermissionsFacade](https://github.com/Orckestra/C1-CMS-Foundation/blob/dev/Composite/C1Console/Security/PermissionsFacade.cs) which takes [EntityToken](https://github.com/Orckestra/C1-CMS-Foundation/blob/dev/Composite/C1Console/Security/EntityToken.cs) as argument and returns the current set of permissions for that element. EntityTokens are what represents all the items in the Console Tree Structure, including pages.

To the get `EntityToken` of a page, you need its underlying `IPage` instance, which then has a `GetDataEntityToken()` method you can call, and then pass to `PermissionsFacade.GetPermissionsForCurrentUser`.

So the final logic would be

1. Do a foreach over all HomePageIds
2. For each HomePageId, get the underlying IPage instance
3. Get the EntityToken for that IPage instance by calling GetDataEntityToken
4. Call  PermissionsFacade.GetPermissionsForCurrentUser
5. See if the list of permissions contain the necessary permission, ie. [PermissionType.Read](https://github.com/Orckestra/C1-CMS-Foundation/blob/dev/Composite/C1Console/Security/PermissionType.cs)

**Comment by ai-fwd** [comment]
Thanks.
