### ISSUE TITLE
List Unpublished Data shows unpublished pages rather than data items

### ISSUE THREAD

**Issue by wwwysocki** [Orckestra/C1-CMS-Foundation#614]
**Summary**

It looks like the "List Unpublish Data" feature is broken. When used,

it shows:
- unpublished pages (see the screenshot below)
- unpublished data items of existing data types (like BlogEntries from the installed package)

it doesn't show:
- unpublished data items of newly created data types

**Repro 1**:

1. Unpublish 1+ page.
2. In the "Data" perspective, select the "Global Data Types" node and click "List Unpublish Data"
3. Check for the unpublished pages from Step 1

**Expected**: None. (It has its own "List Unpublished Pages" in "Content")
**Actual**: Unpublished pages are present

**Repro 2:**

1. Create a new global data type that supports publishing
2. Add 1+ items
3. Save the items without publishing, or unpublish the items that were saved & published
4. Select the "Global Data Types" node and click "List Unpublish Data"
5. Check for the items from Step 3

**Expected**: The items are present
**Actual**: None

![image](https://user-images.githubusercontent.com/14821915/44520616-05c96980-a6d9-11e8-9de3-976429e8c65d.png)

**Comment by mawtex** [comment]
To address Repro 1 I'll set the label to "List Unpublished Content" and ensure the command is available only on the Content perspective (on "Websites"  and "Website Items").

The list will show any unpublished page/data, visible via the Content perspective (be it via Websites, Website Items or any custom trees otherwise added to the Content perspective). 

For Repro 2, you need the data to be accessible via the Content perspective, for it to appear in the list - either by adding the data type to "Website Items" or by some other means, like a custom tree definition.

**Comment by mawtex** [comment]
Fixed with https://github.com/Orckestra/C1-CMS-Foundation/commit/d8739c70c9f48e29815878151180dfc82a794073 and https://github.com/Orckestra/C1-CMS-Foundation/commit/213268890d936f5ea936fe12098e73563ae3bd8a
