### ISSUE TITLE
How to handle legacy function parameters?

### ISSUE THREAD

**Issue by ai-fwd** [Orckestra/C1-CMS-Foundation#637]
I have a razor function that needs to be updated based on user feedback. The function currently has a parameter called "Foo" that is being actively used. In the updated version of the function I want to introduce a new parameter "Bar" that will replace what "Foo" was used for. 

The experience i'm looking for is as follows:
1. The function remains functional with "Foo" after the update to introduce "Bar".
1. The function UI hides "Foo" and shows "Bar" for any new uses.
1. The function shows "Foo" if its already contains a value.

Is this possible, or is there anyway to signal to a user that the function parameter is obsolete?

**Comment by mawtex** [comment]
> The function remains functional with "Foo" after the update to introduce "Bar".

Make "Bar" optional by giving it a default value, see https://docs.c1.orckestra.com/Functions/Razor/Defining-Parameters

> The function UI hides "Foo" and shows "Bar" for any new uses.
> The function shows "Foo" if its already contains a value.

Very likely not, since your parameter is probably of an ordinary type, like String or int - but if "Bar" is of a very unique type, you could achieve what you want using an parameter injection feature. If you inject a type X into our DI container and you have a function taking this type X as a parameter, the parameter will be hidden in UI (except if it has a specific local value). At runtime, if it does not have local value, it will be fed from the DI container. An example of this is parameters of type `RoutedData<SomeDataType>`, see https://docs.c1.orckestra.com/Data/Data-URL-Routing 

Probably the cleanest way would be to create a new function and keep the old one around. If you use "components" you can quietly change the 'behind the scenes function' so users use the same UI steps to insert, they just get the new function UI to config, see https://docs.c1.orckestra.com/Console/CustomizingVisualEditor/Components

**Comment by ai-fwd** [comment]
@mawtex OK that's what I thought from everything I read. I guess I would say that's a feature request from my side because replacing a function across hundreds of sites requires some SQL magic vs the function understanding that something is [obsolete]. 

BTW  do components have the same group/user based permissions as functions?

**Comment by ai-fwd** [comment]
@mawtex yeah it works pretty well -- we're experience some performance issues in the backend but we'll fix that up shortly. It's based on the walking the permissions tree.
