### ISSUE TITLE
[Question] How many concurrent users console can handle? 

### ISSUE THREAD

**Issue by aeont** [Orckestra/C1-CMS-Foundation#650]
Did you performed any tests? Lets say console usage limited just to Media (each user have it's own folder he can see and manage - read / delete / upload). What figures will look like for XML and MS SQL database? 1500 users is real? 5k?

Thank you in advance for your opinion.
@napernik @mawtex @burningice2866  

P.S. Lets say my target is 1500 concurrent users. Feasible? Constrains (I know we have limits for XML database). What figures will look

**Comment by mawtex** [comment]
The highest number of editors I recall seeing is 80 to 90 editors, updating different parts of the content with asymmetrical frequency. They were running on SQL. Back then we worked with them to ensure a good editing experience, so we should be good with that level of editors / activity in the back-end. 

How far that goes towards your 1500 users I don't know, but I'm for sure not expecting the C1 back-end to be happy with 1500 concurrent users. If there is some degree of asymmetric usage (like the users updating less often and across time zones) 1500 "potential users" might work well. 

It would make sense to beef up your server for content editing and using something like our [Cloud Publisher](https://c1.orckestra.com/Add-ons/All/Orckestra.Azure.CloudPublisher) to ensure the load of editing and the load of serving the public is separated.

Likely you want to be on SQL, since XML performance is hurt with a high degree of updates, and I guess a lot of users would give a lot of updates.

I hope this helps.

**Comment by aeont** [comment]
@mawtex thank you for reply. Planned usage is only download and upload files to media archive. And we taking about few files per user max.
