### ISSUE TITLE
Composite NuGet package CompositeC1.Core vs C1CMS.Assemblies

### ISSUE THREAD

**Issue by dragana1011** [Orckestra/C1-CMS-Foundation#797]
Hi,

Did you change Composite NuGet package? What is the difference between CompositeC1.Core (by burningice) and C1CMS.Assemblies (by Orckestra)?

Here, on your profile, it is stated that 6.11 is the latest version of the Composite but NuGet package CompositeC1.Core latest version is 6.9.

If you changed package name and versions continue to be published (after v 6.9) under C1CMS.Assemblies NuGet package, is there an instruction somewhere how to transfer from CompositeC1,Core version 6.9 to C1CMS.Assemlies version 6.11 (6.11.7982.26191).

What I tried:
I am trying to update Composite from my project to a latest version. At the moment, I have 6.9 version
I uninstalled CompositeC1.Core v 6.9 and installed C1CMS.Assemlies version 6.11 (6.11.7982.26191)  and I am have an issue with a namespace from Composite.Core

![image](https://user-images.githubusercontent.com/23667906/156543596-02afe21f-b9ae-42ff-9991-0ed50ea6dcb0.png)

Thank you,
Dragana

**Comment by burningice2866** [comment]
Hi,

The CompositeC1.Core nuget package is from before Composite/Orckestra published any nuget packages themselves. I admit that i haven't been updating CompositeC1.Core lately to the newest version, mostly due to lack of time and interest in C1 anymore. Its hard to see any future of the product, and while it has some interesting ideas in the underlying data types system, its just not able to keep up the state of asp.net today.

I personally found that the C1CMS.Assemblies wasn't meant for public usage but should have been an internal package for Orckestras own use. It doesn't follow common NuGet guidelines for dependencies and versioning and some of the shipped assemblies within the package doesn't always match the version of the package (issue raised here https://github.com/Orckestra/C1-CMS-Foundation/issues/253)

I would be happy to publish the two missing CompositeC1.Core versions if that would help your current situation.

**Comment by dragana1011** [comment]
Hi burningice2866,

Yes that would help my current situation. Thank you so much. Please publish two missing CompositeC1.Core versions.

Dragana

**Comment by burningice2866** [comment]
Version 6.10 and 6.11 are now listed here https://www.nuget.org/packages/CompositeC1.Core

**Comment by dragana1011** [comment]
Great! Thank you.
